# Canon on Nudges 

## Abstract
_Nudging is considered to be “any aspect of the choice architecture that alters people's behaviour in a predictable way without forbidding any options or significantly changing their economic incentives” (Thaler & Sunstein, 2008). Whereas the traditional Rational Choice Theory of Economics would predict that nudges should have no effect on economic decision making because the monetary incentives remain unchanged, mounting evidence from laboratory experiments and field data has shown that nudges can and do affect outcome choices. There are many underlying mechanisms which might explain how nudges are able to alter behaviour. For example, the concept of socially desirable decision making can be traced back as far as Adam Smith’s Theory of Moral Sentiments (Smith, 1790), although many years passed before the field of Behavioural Economics would develop, inspired by findings in psychology. Today we can find nudges being used in many private initiatives and public policies, such as defaults for public organ donation or even decals of flies placed in urinals._

_This canon seeks to explore how the concept of nudging developed, whether nudges are successful at predictably altering behaviours, and what underlying mechanisms might explain why nudges work._

## Table of contents

1. Introduction
2. Concepts and definitions
  * Choice architecture
3. Historical examples of nudging
4. Nudges in modern experiments and public policies
5. Critiques and concerns
6. Mechanisms and limitations
7. Conclusions
8. References

## 1. Introduction
Every day, the basic assumption that people are perfectly rational individuals is disputed, since many times they make non-rational, time-inconsistent decisions. As economists, we need to acknowledge this fact and try to model behaviour considering this complex scenario. This is why studying nudges becomes important; because it focus on how people should behave, taking into account their own “irrationality”. In a context where people not only respond to classic rational or monetary incentives, nudges can contribute by proposing new mechanisms models that can help us understand society, and therefore conduct better policies.

Even though nudges have been used by people all through history, the concept is quite new in economic literature and in public policies or field experiments. We think it is important to systematize this experiences and into a whole body knowledge. This way, we expect to contribute to the field and encourage other economists to study the depths of human behaviour.

Is it good to assume people should behave in a certain way? Can nudges be used in a bad way? Even though there are a lot of moral concerns related to the use of nudges in the private sphere, in advertising and in private companies, in this canon we will focus mostly on this questions and the role of public authorities. This, because we are mainly concerned on how nudges can be applied to public policies, and how authorities can use them to improve the life of the community.
This document is structured as follows: Chapter 2 defines the main concepts and types of nudges. Chapter 3 will briefly show some nudges though history, and chapter 4 will describe some examples of the use of nudges in public and private policies. Chapter 5 provides some of the critiques that nudges have faced, and chapter 6 will make an analysis of such critiques and on when is it better to apply nudges. Finally, chapter 7 will state our main conclusions. day, the basic assumption that people are perfectly rational individuals is violated, since many times they make non-rational, time-inconsistent decisions. As economists, we need to acknowledge this fact and try to model behaviour considering this complex scenario. This is why studying nudges becomes important; because it focus on how people should behave, taking into account their own “irrationality”. In a context where people not only respond to classic rational or monetary incentives, nudges can contribute by proposing new mechanisms models that can help us understand society, and therefore conduct better policies.
Even though nudges have been used by people all through history, the concept is quite new in economic literature and in public policies or field experiments. We think it is important to systematize this experiences and into a whole body knowledge. This way, we expect to contribute to the field and encourage other economists to study the depths of human behaviour.
Is it good to assume people should behave in a certain way? Can nudges be used in a bad way? Even though there are a lot of moral concerns related to the use of nudges in the private sphere, in advertising and in private companies, in this canon we will focus mostly on this questions and the role of public authorities. This, because we are mainly concerned on how nudges can be applied to public policies, and how authorities can use them to improve the life of the community.

This document is structured as follows: Chapter 2 defines the main concepts and types of nudges. Chapter 3 will briefly show some nudges though history, and chapter 4 will describe some examples of the use of nudges in public and private policies. Chapter 5 provides some of the critiques that nudges have faced, and chapter 6 will make an analysis of such critiques and on when is it better to apply nudges. Finally, chapter 7 will state our main conclusions.

## 2. Concepts and definitions
This chapter will describe the concept of nudging and how is it going to be used in this canon. 

Our starting point is the analysis of decision making. There are two different aspects in the analysis of a decision: First of all, there is the normative aspect, which focus on how perfectly rational individuals would make their choices (i.e. they choose the optimal option for themselves). Second, there is the descriptive aspect, which focuses on how people, who are actually not perfectly rational, make decisions in everyday choices (Raiffa, 1982). On an everyday basis, individuals are subject to biases and intuitions that may guide the away from the choices a perfectly rational individual would take. 

A third aspect of decision analysis focuses on how individuals should make their everyday decisions, given that they are not completely rational. This is called the prescriptive aspect of decision making. For example, how could people be more aware of biases, especially when they lead them astray from what they would like to do, given their normative and rational preferences? Some of the questions that are relevant for the prescriptive aspect are “How can people be encouraged to save more?” “What would people need in order to eat healthier?”. 

From this point, we can start developing the concept of nudging. Nudges are some kind of reinforcements (which can be positive or negative), special ways of framing (Kahneman & Tversky, 1981) or suggestions that can influence the way people make decisions, without changing their monetary incentives and in a non-forced way. In public policies, authorities can manage the way choices are presented to individuals, that is, the choice architecture, in a way that they make better decisions, avoiding biases of everyday life.

In this context, “_a nudge is any aspect of the choice architecture that alters peoples’ behaviour in a predictable way without forbidding any options or significantly changing their economic incentives_” (Thaler & Sunstein, 2008). In other words, a nudge specifies how individuals make important economic decisions by forming effective prescriptive techniques with the help of behavioural economics (Thaler & Benartzi, 2004).

There are several ways of nudging individuals into a specific behaviour. Some of the most frequent nudges are explained below:

1.	**Default rules and Status Quo:**
A default is defined as what happens when someone does nothing, but instead follows the pre-set option. A good example is the organ donation system in some countries of Europe, as will be developed in chapter 4.
2.	**Comparisons with the social norm:** 
This nudge will encourage individuals to think about their behaviour in comparison to the behaviour of others. This kind of nudges in the private sphere include, for example, the messages displayed in hotels rooms; instead of saying “_Please reuse your towels_”, they make a sign that says “_Join your fellow guests in helping to save the environment by reusing the towels_”. Chapter 4 will discuss other examples in public policies.
3.	**Increase in ease and convenience:** 
This nudge is very common in cafeterias, where customers can be nudged to make healthier food choices, by placing fruit close to the checkout, instead of candy. This kind of nudge aims to help individuals make better choices by suggesting them in a convenient and easy way.
4.	**Eliciting implementation intentions / self-control:** 
Implementation intentions involve a concrete plan in a specific situation, leading to a better perception and attention to a critical situation. They are usually more successful than setting abstract goals, since the goal-setters must contemplate a series of specific steps and actions. For example, a goal such as “I want to save more money” may be difficult to reach in practice, as compared to an implementation intention, “every time I get a raise, I will increase my savings rate”. These were exactly the findings of the Save More Tomorrow (SMarT) Program, which was a savings program designed for individuals with self-control problems, since it “gives workers the option of committing themselves now to increasing their savings rate later, each time they get a raise” (Thaler & Benartzi, 2004).
5.	**Warnings:** 
We can find this kind of nudge in grocery shops, where every food item is labelled with a green, yellow or red sticker. Such nudging aims to warn and remind people about how certain behaviours can deviate them from their initial goals. 

### Choice architecture
Nudges can have inadvertent effects other than what was intended by the policy makers. It is not always clear which type of nudge or wording will be most effective. It is important to understand the context of the decision-making process and identify which biases or heuristics may be affecting consumers. After this a suitable nudge can be selected dependent on whether policy makers are trying to encourage or discourage actions and whether they hope to influence automatic decision processes (System I responses) or rational decision processes (System II responses) (Ly, Mazar, Zhao, & Soman, 2013). Most often, the formulation of the nudge must then be tested via experiments for a given choice to see what would be most effective for policy applications. 

As economists learn more about the emerging field of nudging, more work must be done to see why nudges are successful under some conditions but unsuccessful or unable to be successfully replicated under other conditions (Newell, 2014). In time, we may find certain common characteristics between successful or failed nudge attempts which can be used as a guideline for when nudges may be practical to apply.

## 3. Historical examples of nudging
While nudging is a relatively new concept in economic literature, the idea behind the concept has been used all through history, not only by policy makers but also by companies, managers in charge of teams and groups of people, etc. This chapter and the next one will discuss the uses of nudging in history and the most recent uses of nudges in public policies, respectively.

The main authors that made the concept nudging known to a broader audience are Richard H. Thaler and Cass R. Sunstein, through the book “_Nudge:  Improving Decisions About Health, Wealth, and Happiness_” (Thaler & Sunstein, 2008). In their book, they explain what nudging is and how this can be implemented in policies, and conclude that nudging is not only bad, but that is can be used to guide us in beneficial directions. However, nudging is a concept that was used already for a long time before Thaler and Sunstein wrote their book, as it is illustrated in the following examples.

We can already see nudging techniques in Europe in the 1700s (Halpern, 2015), period in which the population was growing, but there was not enough food due to wars and revolutions. Therefore, many countries in Europe stated to introduce the potato as a cheap way of reducing faming. However, this food founded a lot of resistance from the people, since it had no smell, no taste, and it was not mentioned in the Bible. As a way of stimulating people to eat potatoes, Frederick the Great (King of Prussia between 1740 and 1786) decided to use a nudging mechanism on the nation, planting potato fields in his own lands and ordering his soldiers to guard them, so that people would think that potatoes were a luxury good. Not surprisingly, when the fields had guards surveilling them, many people started stealing potatoes and planting them in their own yards, increasing its consumption and decreasing the famine.

Other instance on which nudging was used is during the “Dollar-a-day” program in the 1990s, in North Carolina, U.S.A. This program tried to reduce the rate of teenage pregnancy between ages of 12 and 18, specifically through the following nudging mechanism: a dollar would be given to each young woman participating in the program for every day they did not got pregnant. A year after the program had begun, the pregnancy rates had lowered significantly; while before the program it was expected that 3 out of ten young women would get pregnant by the age of 20, the rate of teenagers who got pregnant in the program was of 15% (Brown, 1999).

Another famous example is from the early 1990s, when Schiphol Airport in Amsterdam, the Netherlands, was looking for solutions about how keeping the men’s toilet clean. A nudging mechanism was put into practice, placing the picture of a fly inside of each urinal. Because of this fly, which people consciously don’t like, men were more likely to aim at it. Due to this mechanism, the men’s toilet was way cleaner and the cleaning bill decreased in approximately 80% (Evans-Pritchard, 2013).

While these uses provide some historic evidence of the uses of nudging, it wasn’t until the 20th and 21st century that academics started developing literature and documenting field experiments and policies that used nudging mechanisms. The following chapter will briefly discuss some of the main uses of different types of nudges in public policies and field experiments in nowadays. 

## 4. Nudges in modern experiments and public policies
As illustrated before, the concept of nudging offers lots of possibilities in changing people’s behavior, which can be especially convenient for changing undesirable conducts. After successful experiences, such as the one with the “fly-toilets” on Schiphol Airport, experimenters, businesses and policy makers quickly got convinced of the effectiveness of nudging’s key feature: subtly steering people’s behavior without them being aware of it and without (significantly) changing their options. Some examples of these experiments and applications in the real world are discussed in this paragraph. 

Probably the most famous example of a nudging based study is Johnson and Goldstein, who demonstrated the difference between opting in- and opting out-systems of organ donation (Johnson & Goldstein, 2003) among countries, reporting a  significantly higher percentages of organ donors in the countries with an opt out system. This is a clear example of how the status quo bias works in a nudging context. 

Figure 1: Comparisons between countries with an opt-in system and an opt-out system
![Figure 1: Comparisons between countries with an opt-in system and an opt-out system] (http://1.bp.blogspot.com/-FX4E9dMOZM8/VmT7X7ROW3I/AAAAAAAAA_0/ocasr8UL_p4/s1600/27%2BNormal%2BInvestors%2B-%2BStatus%2BQuo.png)

Source: [http://www.2muchcents.com/2015/12/normal-investors-status-quo.html] (http://www.2muchcents.com/2015/12/normal-investors-status-quo.html)

This kind of nudges, as described in the first chapter, rely on the fact that people in general will keep the status quos. This is also documented by Bernartzi and Thaler; Employees who are by default enrolled in at the Save More Tomorrow Program, automatically increase the percentage of their wage devoted to saving, from a 3,5% 40 months earlier to the program, to an average of 13.5% after the program (Thaler & Benartzi, 2004). 

Other often-observed drivers of nudges are social norms. This was well documented in a public policy field experiment by Schultz et al.; providing the opportunity to a citizen to compare their energy usage with their neighbor’s usage leads the citizen to a more efficient use of energy (Schultz, Nola, Cialdini, Goldstein, & Griskevicious, 2007). Other example of this nudge is provided by the Behavioral Insights Team of the UK, who studied the people’s behavior when paying their phone bills: citizens who received social normative messages (“_9 out of 10 people from your town pay their taxes on time_”) have a 15% more probabilities of paying their bills on time, compared to people who don’t receive such message (Behavioral Insights Team, 2011). Curiously, while this type of nudge was quite successful, Torgler has found in Switzerland that other type of messages with a moral rather than social content (“_paying your taxes is not the right thing to do_”) don’t have an effect on the compliance rate (Torgler, 2004). 

Nudges can also warn people about consequences of their acts in different forms. This kind of nudge was described in a field study conducted in Pennsylvania  (Small, Lowenstein, & Slovic, 2007), which tried to raise the amount of people donating money to charity by showing them an identifiable victim (for example, the picture and the name of a poor girl). In their paper, the authors concluded that people donated almost twice the amount of money, compared to participants who were only confronted with a statistical report of victims. Another documented case of nudging being used in public policies is described by Wilson et al. In this paper (Wilson, Bogomolova, & Buckley, 2015) demonstrate how low-fat milk with the message “_Pick me! I am low calorie_” leads to an increase in the demand for low-fat milk, but only on short term. After three months, the effect of the sign completely disappeared. 

Other interesting but unsuccessful public policy, was conducted in France and assessed by Basso and Oullier, where the traditional disease-related messages on cigarette packages had been replaced by an image which shows a smoking adolescent on his knees, while facing a standing adult male. The purpose of this field experiment was to surprise smoking teenagers and to create a shock effect based on moral consequences rather than health consequences. However, teenagers started to smoke more as they craved for some cigarettes after seeing this suggestive image. They concluded that this method was unsuccessful, even though it stimulated political and ethical debates about smoking (Basso & Oullier, 2011).

As we can see from these previous examples, nudging is not always a successful method to change behavior. This may be because people are habituated to their behavior, or because the effect may disappear on the longer run. In fact, if the mechanisms that are behind a person’s decision making process are not well understood and not well taken into account, nudging will not work as expected. This is way decision architects must always conduct a careful research to understand what’s behind people’s decision processes.

Besides this consideration, decision architects must be aware of how nudges can change people’s decisions, understanding that there is a responsibility behind the use of such mechanisms. The next chapters will focus on the main critiques made to nudging, while the last chapter will make an analysis on these critiques and on how nudges should be used in order to help people.

## 5. Critiques and concerns
In this part we will stand out four critiques made to nudges and what they represent to a persons’ liberty as well as to what they could represent to governments and their various forms of interventions:

One of the most recognized critique of behavioral economics, and moreover to nudges, is the Harm Principle set forth by John Stuart Mill in his book _On Liberty_. The basic notion of harm principle is that of “_letting people harm themselves as long as they do not harm anyone else_”  (Mill, 1869). In this sense, some authors emphasize that the idea of indirectly suggesting people what to decide –which is what a nudge is created for–, may be contrary to that of Stuart Mill and his principle on liberty. The main concern is that, when faced with a nudge, an agent may be losing her freedom to decide, even if the decision is to harm her own self. In the government side of the argument, Mill advocates that treating adults as if they were not rational beings deciding for themselves in their best self-interest may be having a paternalistic approach and thus not exercising power righteously. 

A second more recent critique, and related to that of John Stuart Mill, is that most people learn from their mistakes, so why is letting them make a few mistakes is a bad idea? Recent research that looks into late payment fees suggest that “_consumers learn more about the existence and magnitude of fees when they knowingly or accidentally trigger them_” (Agarwal, Driscoll, Gabaix, & Laibson, 2013). The authors suggest that people learn from their mistakes and moreover –in this specific case– when faced with a fee for their mistake, these same consumers act in a more vigilant manner towards their credit card usage thereof. The evidence that Agarwal et al. give is that people not only learn from their mistakes, but that they are normally more concerned with their credit and the avoidance of a fee when committing a mistake beforehand. In other words, in order to learn, sometimes a mistake must be made. Therefore, if nudging people not to commit any mistake is limiting their freedom as well as prohibiting them to learn from their mistakes, then why is it that governments constantly insist on nudging people towards their best self-interest, assuming that they by themselves cannot do it?

Here, a traditional response of the nudging advocates is that there are several situations in which most people cannot learn from their mistakes, or situations in which their mistakes could be potentially costly, e.g. when buying a house, when choosing a life insurance, etc. Their conclusion is that, sometimes, some type of nudge for these situations could help people avoid costly mistakes. 

A third critique, and more related to the use of public policy, is the possibility of unintended consequences when using nudges. This critique is based on the idea that government is worse than we are (as individuals) at knowing what is good for us, proof of this is that there are a lot of policies that have backfired. One of the main reasons identified so far is that policy makers do not fully understand the effects that their policies may have in the end. For example, Robert Cialdini’s research nudged subjects for reducing crime rates by giving a message to people of “_don’t steal_”, and for reasons yet unknown, the message got interpreted as a “_stealing is a common and socially acceptable behavior_” and increased crime rates in the end (Cialdini et al., 2006). This example is added to the long list of nudges that did not work and that backfired in the end, perhaps due to the fact that people in charge of creating these nudges could not predict what was really going to happen. The existence of these cases has raised several questions in the usage of nudges. 

One fourth, but not final concern for using nudges, is that they can be coercive. Here, the line between nudging, coercion and manipulation has proved to be a very fine and crossable one. Although most of the coercive concerns for nudges have been identified in the private sector, most nudges, even the public ones, could be coercive and manipulative in several degrees. 

As stated in this chapter, most critiques are related to the person’s freedom of choice, and the fact that a policy maker or a design architect shouldn’t always have all the power to decide what decision is better, neither she has all the information to decide what nudge is best to apply. These aspects are well known to researchers who had developing the literature on nudging, and thus they had developed certain arguments on why and when a nudge is a good choice. Next chapter will develop these arguments, and will also give some guidelines that should be take into account in the discussion. 

## 6. Mechanisms and limitations
As Thaler and Sunstein state, “_people will need nudges for decisions that are difficult and rare, for which they do not get prompt feedback, and when they have trouble translating aspects of the situation into terms that they can easily understand_” (Thaler & Sunstein, 2008). But why might people need nudges? Unlike the perfectly rational _homo economicus_, people exhibit many sub-perfect behaviours. We have flaws in calculations, time inconsistencies, poor self-control, imperfect follow through, biases, and loss aversion. Things like social norms, priming, framing, and anchoring can change how our choice outcomes. Rules of thumb or heuristics are often used to make decisions because of lack of numeracy or difficulties in making calculations. For example, a person may have difficulties assessing how a choice of wine will relate to welfare: which one will taste the best? This person may use higher price as a heuristic to judge the quality or the wine although they may prefer the taste of a cheaper bottle.  The search cost to find their most preferred bottle may be too large such that they satisfice rather than maximize their utility. Another example of sub-optimal choice is dieting and exercising. Someone may determine the best course of action, but not be able to follow through with their resolutions because of high costs now, and delayed benefits which are only received much later (Thaler & Sunstein, 2008). However, all decision architects should be aware of the effects of nudging on people’s decision processes, and should be committed to use these effects to help people instead of helping themselves or pursuing a totally different goal. 

In this context, Thaler and Sunstein also argue that nudges should meet three conditions before they can be used to change people’s behaviour. First, nudges should “_help people save more, eat better, invest more wisely, and choose better insurance plans and credit cards—in each case only when they want to_”. Therefore, we can say that nudges should help people to make better choices if that is what they would like to do. Second, nudges should have a low opt-out cost for anyone wishing to avoid the nudge; nudges should not force people into a particular choice or restrict their freedom to deviate from the prescribed choice. Third, because a nudge is often inevitable in the construction of a choice architecture, the government should select a nudge which optimizes welfare. Since there is often an implied nudge within any choice architecture, allowing inertia or random choice to select the nudge is less optimal than a government intervening to choose the nudge which would be most beneficial to consumers. Their arguments presume that the choice architect or government is in fact benevolent and interested only in improving the welfare of its citizens. They also assume that the choice architects or experts will be better able to lead consumers to an optimal choice than the consumers are able to choose individually. Lastly, it presumes that the wants or preferences of consumers are known to the policy makers, but also that their preferences are comparable or relatively homogenous such that the same nudge would lead to an optimal choice for most consumers. Otherwise, it may be the case that while some consumers are helped by the nudge others are hurt by it (Schlag, 2010).

## 7. Conclusions
Nudging is certainly not a new technique, and it has proved it can be very effective at shaping people’s behaviours. However, there’s a still much research to be done to understand the mechanisms behind nudges, and to discover what non-economic incentives are important in order to model human choices.

Although many moral and ethical concerns can arise from the use of nudges, such as whether or not the policy maker is better positions to prescribe a course of action, or whether or not they limit freedom of choice, we cannot overlook the fact that nudges are present in our lives. Even if a decision architect decides not to use an explicit nudge, there will still be an implicit nudge within the decision framework.  Whenever a message is delivered, or a product or program is offered, people will have to decide how to react based on the way the information they perceive is presented. 

It is our responsibility acknowledge the inherent nature of nudges in choice architecture, and to study the mechanisms through which nudges work, such that choice architects can wilfully select those nudges which increase welfare.

## 8. References
*	Agarwal, S., Driscoll, J. C., Gabaix, X., & Laibson, D. (2013). _Learning in the credit card market_. Retrieved from Harvard University: [http://scholar.harvard.edu/files/laibson/files/learning_credit_042413.pdf] (http://scholar.harvard.edu/files/laibson/files/learning_credit_042413.pdf)
*	Basso, F., & Oullier, O. (2011). _Smokers are suckers: Should incongruous metaphors be used in public health prevention?_ Amiran Journal of Public Health, 101(2), 203-204.
*	Behavioral Insights Team. (2011). [www.gov.uk] (www.gov.uk). Retrieved from Behaviorals Insight Team: [https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/60537/Behaviour-Change-Insight-Team-Annual-Update_acc.pdf] (https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/60537/Behaviour-Change-Insight-Team-Annual-Update_acc.pdf)
*	Brown, H. N. (1999). _Preventing secondary pregnancy in adolescents: A model program._ Healthcare for Women International, 20(1), 5-15.
*	Cialdini, R. B., Demaine, L. J., Sagaring, B. J., Barret, D. W., Rhoads, K., & Winter, P. L. (2006). _Managing social norms for persuasive impact_. Social Influence, 1(1), 3-15.
*	Evans-Pritchard, B. (2013). _Works that Work_. Retrieved from _Aiming to reduce cleaning costs_: [https://worksthatwork.com/1/urinal-fly] (https://worksthatwork.com/1/urinal-fly)
*	Halpern, D. (2015). _Inside the nudge unit_. Virgin Digital.
*	Johnson, E. J., & Goldstein, D. (2003). _Do defaults save lives?_ Science, 302 (5649), 1338-1339.
*	Kahneman, D., & Tversky, A. (1981). _The framing of decisions and the psychology of choice_. Science, 221(4481), 453-458.
*	Ly, K., Mazar, N., Zhao, M., & Soman, D. (2013). _A practicioner's guide to nudging_. Rotman School of Management Working Paper.
*	Mill, J. S. (1869). _On Liberty_. London: Longman, Roberts & Green.
*	Newell, B. (2014). _'Nudging' people towards changing behavior: What works and why (not)?_ Retrieved October 2016, from The Conversation: Academic Rigour, Journalistic Flair: [http://theconversation.com/nudging-people-towards-changing-behaviour-what-works-and-why-not-27576] (http://theconversation.com/nudging-people-towards-changing-behaviour-what-works-and-why-not-27576)
*	Raiffa, H. (1982). _The art and science of negotiation_. Cambridge: The Belknap Press of Harvard University.
*	Schlag, P. (2010). _Nudge, choice architecture and libertarian paternalism_. Michigan Law Review, 108, 913-924.
*	Schultz, P. W., Nola, J. M., Cialdini, R. B., Goldstein, N. J., & Griskevicious, V. (2007). _The constructive, destructive and reconstructive power of social norms_. Psychological Science, 18(5), 429-434.
*	Small, D. A., Lowenstein, G., & Slovic, P. (2007). _Sympathy and callousness: The impact of deliberative thought on donations to identificable and statistical victims_. Organizational Behavior and Human Decision Processes, 102(2), 143-153.
*	Smith, A. (1790). _The theory of moral sentiments_. Library of Economics and Liberty.
*	Thaler, R., & Benartzi, S. (2004). _Save more tomorrow: Using behavioral economics to increase employee saving_. Journal of Political Economy, 112.
*	Thaler, R., & Sunstein, C. (2008). _Nudge: Improving decisions about health, wealth and happiness_. Yale University Press.
*	Torgler, B. (2004). _Moral persuasion: An alternative tax policy strategy? Evidence from a controlled field experiment in Switzerland_. Economics of Governance, 5(3), 235-253.
*	Wilson, A. L., Bogomolova, S., & Buckley, J. D. (2015). _Lack of efficacy of a salience nudge for substituting selection of lower-calories for higuer-calories milks in the work place_. Nutrients, 7(6), 4336-4344.

